matrix:
  include:
      # Reference for macOS Versions:
      # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
    - language: objective-c
      sudo: required
      os: osx
      osx_image: xcode10
      script:
        - swift build
        - swiftlint --strict
        - swift test
    - sudo: required
      env:
        - DOCKER_CONTENT_TRUST=1
        - SWIFT_BUILD_TOOLS_SHA256=bafbce9275422f5cd74bea0f5fe00749e7aa9458693e3d37c40c59cd4ac297dd
      before_install:
        # Update Docker
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y install docker-ce
      script:
        - docker run --rm --volume=$(pwd):/usr/src/ bluk/docker-swift-build-tools@sha256:$SWIFT_BUILD_TOOLS_SHA256 swift build
        - docker run --rm --volume=$(pwd):/usr/src/ bluk/docker-swift-build-tools@sha256:$SWIFT_BUILD_TOOLS_SHA256 swiftlint --strict
        - docker run --rm --volume=$(pwd):/usr/src/ bluk/docker-swift-build-tools@sha256:$SWIFT_BUILD_TOOLS_SHA256 swift test
