matrix:
  include:
      # Reference for macOS Versions:
      # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
    - language: objective-c
      sudo: required
      os: osx
      osx_image: xcode9.4
      before_install:
        - brew update
        - brew upgrade swiftlint
      script:
        - swift build
        - swiftlint --strict
        - swift test
    - sudo: required
      before_install:
        # Update Docker
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y install docker-ce
      script:
        - docker run -it --name swift --volume=$(pwd):/usr/src/ --rm bluk/docker-swift-build-tools:4.1 swift build
        - docker run -it --name swift --volume=$(pwd):/usr/src/ --rm bluk/docker-swift-build-tools:4.1 swiftlint --strict
        - docker run -it --name swift --volume=$(pwd):/usr/src/ --rm bluk/docker-swift-build-tools:4.1 swift test
